name: Validate HACS repository

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest

    steps:
      - name: Zeige Dateien
        run: ls -al
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@22.5.0
      