name: Validate HACS repository

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HACS Action
        uses: hacs/action@main
