name: Validate HACS repository

on:
  workflow_dispatch: # manuelles Auslösen über GitHub UI
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HACS Action
        uses: hacs/action@22.5.0
